Revert "IMS: Remove API and constants related to ECT."
Fixes userspace error when making call over LTE (VoLTE): E AndroidRuntime: java.lang.NoSuchMethodError: No static method isCallTransferEnabled(Landroid/content/Context;)Z in class Lorg/codeaurora/ims/utils/QtiImsExtUtils; or its super classes (declaration of 'org.codeaurora.ims.utils.QtiImsExtUtils' appears in /product/framework/ims-ext-common.jar)

This reverts commit da40ef630e655574019c4956851c5f318d2882e8.

Change-Id: Ie533bacc920df05d59a367ead78f67603aa4bb47